clone:
  git:
    when:
      event:
        - push
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  docker-latest:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "8.2/sid/cli/Dockerfile"
      platforms: linux/riscv64
      tag: latest
    when:
      event:
        - push
      platform: linux/riscv64

  docker-latest-8.2:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/madelineproto
      dockerfile: "8.2/sid/cli/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2
    when:
      event:
        - push
      platform: linux/riscv64

depends_on:
  - variants