platform: linux/riscv64

clone:
  git:
    when:
      event:
        - push
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  alpine-cli:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/php
      dockerfile: "8.2/alpineedge/cli/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2-alpine
      cache_from: type=registry,ref=danog/php:8.2-alpine
      cache_to: type=inline
    when:
      event:
        - push

  sid-cli:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/php
      dockerfile: "8.2/sid/cli/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2
      cache_from: type=registry,ref=danog/php:8.2
      cache_to: type=inline
    when:
      event:
        - push


  alpine-fpm:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/php
      dockerfile: "8.2/alpineedge/fpm/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2-fpm-alpine
      cache_from: type=registry,ref=danog/php:8.2-fpm-alpine
      cache_to: type=inline
    when:
      event:
        - push

  sid-fpm:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/php
      dockerfile: "8.2/sid/fpm/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2-fpm
      cache_from: type=registry,ref=danog/php:8.2-fpm
      cache_to: type=inline
    when:
      event:
        - push
