platform: linux/arm64 # Connected via buildx to starfive2

clone:
  git:
    when:
      event:
        - push
    image: woodpeckerci/plugin-git:v1.5.0
    settings:
      depth: 1
      lfs: false
      recursive: false
      tags: true

pipeline:
  alpine-cli:
    image: docker:cli
    secrets: [docker_username, docker_password]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
      - cd "8.2/alpineedge/cli/"
      - docker buildx create --use --name wp --driver remote tcp://192.168.69.206:1234
      - docker buildx build --platform linux/riscv64 . -t danog/php:8.2-alpine
      - docker push danog/php:8.2-alpine
    when:
      event:
        - push

  sid-cli:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/php
      dockerfile: "8.2/sid/cli/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2
      cache_from: type=registry,ref=danog/php:8.2
      cache_to: type=inline
    when:
      event:
        - push


  alpine-fpm:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/php
      dockerfile: "8.2/alpineedge/fpm/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2-fpm-alpine
      cache_from: type=registry,ref=danog/php:8.2-fpm-alpine
      cache_to: type=inline
    when:
      event:
        - push

  sid-fpm:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: danog/php
      dockerfile: "8.2/sid/fpm/Dockerfile"
      platforms: linux/riscv64
      tag: 8.2-fpm
      cache_from: type=registry,ref=danog/php:8.2-fpm
      cache_to: type=inline
    when:
      event:
        - push
